### ISSUE TITLE
[Question] Minecraft EULA

### ISSUE THREAD

**Issue by SamKemp** [KaiKikuchi/ServerRedirect#3]
How does this mod work in terms of the EULA, I ask as in the FAQ Mojang posted they said:

> What counts as a server? Are proxies one big server, or lots of smaller ones?
A server is something a user connects to with their client. The user is on a different server when they leave one and manually join another (in the multiplayer screen). Virtual servers and proxies make no difference; to the client it’s the same server.

**Comment by Brend-Smits** [comment]
I’m confused why the EULA matters for this mod tbh 0o

**Comment by KaiKikuchi** [comment]
With this mod, clients are connecting to different servers. The server address is different. I am not a lawyer, but I would consider servers using this mod "lots of smaller ones".

The mod just simulates the player manually leaving the server and manually joining another in the multiplayer screen.

**Comment by KaiKikuchi** [comment]
To the client, they're different servers.

I bet you are asking because of this part:
> Can I charge access to a specific part of my server, such as a minigame or world?
No, you cannot charge for any part of a server. Only the access. Once on a server, all players must have the same gameplay privileges. You may make a different server which features “premium” areas, and charge for access to that server instead, but the benefits cannot carry between servers.

If you have more EULA related questions or similar, feel free to keep commenting on this issue.
