### ISSUE TITLE
[Request] Support for Target Selectors

### ISSUE THREAD

**Issue by kencinder** [KaiKikuchi/ServerRedirect#5]
eg `/redirect <address> @p`

**Comment by KaiKikuchi** [comment]
Hello.

Instead of implementing target selectors (that would be time consuming), I'm just adding a radius option that will just teleport all players around the command sender within a certain distance.

Example: `/redirect [Address] r=10` will redirect all players to the specified address within 10 blocks from the sender (either the player that runs the command, or the command block). Hopefully this will be enough to solve the `@p` issue

**Comment by KaiKikuchi** [comment]
Please try this: https://github.com/KaiKikuchi/ServerRedirect/releases/tag/v.1.3.8-BETA1

**Comment by kencinder** [comment]
I was hoping for something that would work via command block etc, I'll give that build a shot as soon as possible.

**Comment by KaiKikuchi** [comment]
Yes, that will work. Command blocks are supported.

**Comment by kencinder** [comment]
I make use of command blocks to create portals, 1 with an /execute targeting specific coordinates and another for particle effects.

The following does not work, coords and everything else within are correct and works with vanilla TP and Sponge plugins like Nucleus for /tppos and /world tp

`/execute @p[x=31,y=95,z=23,dy=1,dz=2] ~ ~ ~ redirect myserverhere r=3`

I've tried dropping the target selector for the execute, using different selectors etc. As noted in the other issue for permissions, radius does work when I issue it myself.

**Comment by KaiKikuchi** [comment]
Try https://github.com/KaiKikuchi/ServerRedirect/releases/tag/v.1.3.8-BETA2 with this command: `/execute @p[x=31,y=95,z=23,dy=1,dz=2] ~ ~ ~ redirect myserverhere -`. Also please specify your server version.

**Comment by kencinder** [comment]
Not working with the above command.

I'm running spongeforge-1.12.2-2705-7.1.0-BETA-3190
